Repository numerique-gouv/oots-france, pull requests merged in 2024-05, with the labels that each got.

#2 Ajoute configuration frontal nginx
  .gitignore
  docker-compose.yml
  nginx.template/conf/nginx.conf
  nginx.template/scripts/init-letsencrypt.sh
Labels: enhancement

#3 Ajout route `GET /ebms/messages/reponseJustificatif`
  src/routes/routesEbms.js
  test/routes/routesEbms.spec.js
Labels: enhancement

#4 Rends message de réponse conforme aux règles de validation
  src/ebms/reponseVerificationSysteme.js
  test/ebms/reponseVerificationSysteme.spec.js
  test/ebms/utils.js
Labels: bug

#6 Injecte l'identifiant de type de justificatif dans la requête
  src/api/pieceJustificative.js
  src/ebms/requeteJustificatif.js
  test/api/pieceJustificative.spec.js
  test/ebms/requeteJustificatif.spec.js
Labels: enhancement

#8 Déporte code site vitrine vers un projet à part
  .env.oots.template
  .env.template
  docker-compose.yml
  mockFCPlus.js
  nginx.template/conf/nginx.conf
  nginx.template/scripts/init-letsencrypt.sh
  server.js
  src/adaptateurs/adaptateurChiffrement.js
  src/adaptateurs/adaptateurEnvironnement.js
  src/adaptateurs/adaptateurFranceConnectPlus.js
  src/api/connexionFCPlus.js
  src/api/creationSessionFCPlus.js
  src/api/deconnexionFCPlus.js
  src/api/destructionSessionFCPlus.js
  src/modeles/fabriqueSessionFCPlus.js
  src/modeles/sessionFCPlus.js
  src/ootsFrance.js
  src/routes/middleware.js
  src/routes/routesAuth.js
  src/routes/routesBase.js
  src/vues/pageAccueil.mustache
  test/api/connexionFCPlus.spec.js
  test/api/creationSessionFCPlus.spec.js
  test/api/deconnexionFCPlus.spec.js
  test/api/destructionSessionFCPlus.spec.js
  test/mocks/middleware.js
  test/modeles/fabriqueSessionFCPlus.spec.js
  test/modeles/sessionFCPlus.spec.js
  test/routes/middleware.spec.js
  test/routes/routesAuth.spec.js
  test/routes/routesBase.spec.js
  test/routes/serveurTest.js
Labels: code

#9 [NETTOYAGE] Supprime gestion cookie session devenue inutile
  .env.oots.template
  package-lock.json
  package.json
  src/adaptateurs/adaptateurEnvironnement.js
  src/ootsFrance.js
  test/routes/serveurTest.js
Labels: code, dependencies

#10 [NETTOYAGE] Suppression règles linter devenues inutiles
  .eslintrc.js
Labels: code

#11 Mets à jour fichier `README.md`
  README.md
Labels: documentation

#12 Supprime l'identifiant eIDAS de la trame ebms
  .env.oots.template
  src/adaptateurs/adaptateurEnvironnement.js
  src/api/pieceJustificative.js
  src/ebms/requeteJustificatif.js
  src/routes/routesRequete.js
  test/api/pieceJustificative.spec.js
  test/ebms/requeteJustificatif.spec.js
  test/routes/serveurTest.js
Labels: code
