Repository numerique-gouv/oots-france, pull requests merged in 2024-09, with the labels that each got.

#25 Mets à jour dépendances
  package-lock.json
  package.json
Labels: dependencies

#29 Factorisation erreurs EBMS pour simplifier leur traitement
  src/api/pieceJustificative.js
  src/erreurs.js
Labels: code

#30 [FIX] répare les dépendances à l'instanciation du serveur
  server.js
Labels: bug

#31 Initialise dépôt requêteurs avec données annuaire
  .env.oots.template
  server.js
  src/adaptateurs/adaptateurEnvironnement.js
  src/depots/depotRequeteurs.js
Labels: enhancement
