Repository numerique-gouv/oots-france, pull requests merged in 2024-08, with the labels that each got.

#16 Trouve le type justificatif depuis le code démarche
  src/api/pieceJustificative.js
  src/depots/depotServicesCommunsLocal.js
  src/erreurs.js
  test/api/pieceJustificative.spec.js
  test/constructeurs/constructeurDepotServicesCommuns.js
  test/depots/depotServicesCommunsLocal.spec.js
  test/routes/routesRequete.spec.js
  test/routes/serveurTest.js
Labels: enhancement

#18 Script pour lire les logs Domibus
  scripts/logsDomibus.sh
Labels: enhancement

#19 Réduis timeout tests
  package.json
Labels: enhancement

#21 Rétablissement d'un frontal NGinx
  README.md
  docker-compose.yml
  nginx.template/conf/nginx.conf
  nginx.template/scripts/init-letsencrypt.sh
  scripts/start.sh
Labels: enhancement

#22 MIise à jour dépendances
  package-lock.json
Labels: dependencies

#23 [NETTOYAGE] Suppression dépendance superflue (mustache-express)
  package-lock.json
  package.json
  src/ootsFrance.js
Labels: code, dependencies

#24 Mets à jour les dépendances suite à npm audit
  package-lock.json
Labels: dependencies
